[package]
name = "monitor-latency-check"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12"
winit = "0.26.1"
serialport = "4.0.1"
log = "0.4"
env_logger = "0.9"
pollster = "0.2"
clap = { version = "3.0.16", features = ["derive"] }
anyhow = "1.0.56"
