[package]
authors = ["dskkato"]
name = "gpio-controller"
edition = "2021"
version = "0.1.0"

[dependencies]
panic-halt = "0.2"
wio_terminal = "0.5.0"
embedded-hal = "0.2"
cortex-m = "0.7.4"
heapless = "0.7.10"
usb-device = "0.2"
usbd-serial = "0.1"